{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 118136,
          "sha512": "9aff573c69ef0a28cc1923aa595cda2474a477a6d1896bbea2209d6fe9a557e8b599bd527ba97e20845d9ecd8076166494ce5480fcc9142a2ccc8498d733389b",
          "sha256": "442d27defc4e1585215f151fbf4eb4fc32f12dfc92a58abe938fedf349e2f6dd",
          "sha1": "e29abdb169e6fd2428461ba29dcaa41dcceda7aa",
          "md5": "40de20ce1585b9a37c24b8cff5c8fa1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.32"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 118136,
          "sha512": "9aff573c69ef0a28cc1923aa595cda2474a477a6d1896bbea2209d6fe9a557e8b599bd527ba97e20845d9ecd8076166494ce5480fcc9142a2ccc8498d733389b",
          "sha256": "442d27defc4e1585215f151fbf4eb4fc32f12dfc92a58abe938fedf349e2f6dd",
          "sha1": "e29abdb169e6fd2428461ba29dcaa41dcceda7aa",
          "md5": "40de20ce1585b9a37c24b8cff5c8fa1a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "size": 81116721,
          "sha512": "b5f6fd000ab0455da122cbf859bb9ae4d19e3e55db6c2a8fcbd758a1e3ccf80d29d5291ea523c573d8a006ba58d888e62aeed1ad7936ffe35aef75e383b4bb24",
          "sha256": "4b70a56baee23a798f553d2b2423c4734921c998fc5f723d56b973ef0a33bdbc",
          "sha1": "66943ceabcc9f743f17fd723a55e967288b5fff3",
          "md5": "ef3da946ee9978c11a048f6f74efaab5"
        }
      ]
    }
  ]
}
