{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 101774,
          "sha512": "a1b6df68e96d515d243705d38da2fe48db891942ab61965149fb9f77f55b8eaff79351984f8d47487a934a29a43ac9042e50766b24b16a9b2edc11bd8f77976e",
          "sha256": "00a9c310c6e11594996e433d811333ed8dcaabf1a4db671449f7a1b521ef30cc",
          "sha1": "3938a6c790f0c1f9bd8cf5c1095b4e8c530f4cf7",
          "md5": "4453724831e0b43f8560630f465604e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.29"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 101774,
          "sha512": "a1b6df68e96d515d243705d38da2fe48db891942ab61965149fb9f77f55b8eaff79351984f8d47487a934a29a43ac9042e50766b24b16a9b2edc11bd8f77976e",
          "sha256": "00a9c310c6e11594996e433d811333ed8dcaabf1a4db671449f7a1b521ef30cc",
          "sha1": "3938a6c790f0c1f9bd8cf5c1095b4e8c530f4cf7",
          "md5": "4453724831e0b43f8560630f465604e1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "size": 77311748,
          "sha512": "4742c29f9ba37c25e41bbd237c422aeafdd9b368de0fe073530e29e74ea97184b3e4a0729fccccc3194bd00029dedd48bf2894c85a2b63e935d894103d8ff4d0",
          "sha256": "02765ac2d2ded92483d127a68fc2793b5105a2072cc6c20becad210c867c5865",
          "sha1": "1b0bd3565d40e5facd84e9f1c9f6a74241fbdfcd",
          "md5": "9f6224c572a9c8b562a749848608e450"
        }
      ]
    }
  ]
}
