{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.1-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 118237,
          "sha512": "ff967abda9e0a0e7dcc344c99a74adf160eef778b4163025ca6faf12fe86c36e81c7cde32bf4f9eba5074b3c1e5dc10890e816c89dc33f320e900abad9705739",
          "sha256": "f14f49cfdb8c41b53b1896c43d2000038f7f209ed51b34861e6d98f4d510b209",
          "sha1": "e16d20aab546884b2a213fa26122730c17261e00",
          "md5": "59c0c10bb8cc4b25bfdd33d90734e873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.32"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL.jar",
          "size": 118237,
          "sha512": "ff967abda9e0a0e7dcc344c99a74adf160eef778b4163025ca6faf12fe86c36e81c7cde32bf4f9eba5074b3c1e5dc10890e816c89dc33f320e900abad9705739",
          "sha256": "f14f49cfdb8c41b53b1896c43d2000038f7f209ed51b34861e6d98f4d510b209",
          "sha1": "e16d20aab546884b2a213fa26122730c17261e00",
          "md5": "59c0c10bb8cc4b25bfdd33d90734e873"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.1-TRIAL-all.jar",
          "size": 80952115,
          "sha512": "bfcf4b039a5431b58935909095758316be002169f0fe90e2bf5a27ef6fabb522577c7395130425fa47559dc2939fd721a464e0e73196da2182037b85551dc7bd",
          "sha256": "eb52bd6c500b00303fab0baf7194e2649e1acdbcc27c830a483ae0420298b19c",
          "sha1": "c7bb565f22a7ff6a561c053ff8aca09a76178d32",
          "md5": "ac044f2da5ec1b6f366f0dd66de1ef44"
        }
      ]
    }
  ]
}
