{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.4-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.4-TRIAL.jar",
          "url": "specmatic-grpc-0.0.4-TRIAL.jar",
          "size": 191485,
          "sha512": "48a729517e187037f0da7176ce810714ec4d9726df4e8059851cb785a7075d6e06e15c885ba545b3c96aa3bb8e284a66b2acae4573f6e8499498581a5b0f7a43",
          "sha256": "b46f072116070887fe8c4b1f8626e33176cdd8de6f2b2b28383a14b577e69686",
          "sha1": "cb434c4b4dd1d37a3a385a9bf263ffc0a96f3e0e",
          "md5": "b94602742f925433c8cf0892e99e54cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.4-TRIAL.jar",
          "url": "specmatic-grpc-0.0.4-TRIAL.jar",
          "size": 191485,
          "sha512": "48a729517e187037f0da7176ce810714ec4d9726df4e8059851cb785a7075d6e06e15c885ba545b3c96aa3bb8e284a66b2acae4573f6e8499498581a5b0f7a43",
          "sha256": "b46f072116070887fe8c4b1f8626e33176cdd8de6f2b2b28383a14b577e69686",
          "sha1": "cb434c4b4dd1d37a3a385a9bf263ffc0a96f3e0e",
          "md5": "b94602742f925433c8cf0892e99e54cb"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.4-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.4-TRIAL-all.jar",
          "size": 97080087,
          "sha512": "eb0eaae15c086c8b1a39edcd396f41c72747b75f97c5c2d89890d5b5f60a131b2b9f660c302f66efb5addc806061d5e2b13ca7b054a8f8ded30ba87827253568",
          "sha256": "cd3d3db35bc9e2878d8308f54a28c9d6dcfed7cd39cbdd08ae97ed08b34c8259",
          "sha1": "5dc3a303b4b248d4abaabb317adf0fcb89c80f6e",
          "md5": "da051c6aa093a573d86c3006575fd942"
        }
      ]
    }
  ]
}
