{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 168685,
          "sha512": "0556e5a27060276cbbaaad64cc3650df52d1a403d5af0466080925a51a71d57c7e594f5ae728e65e1e90dd382b1f55c86bef56a7f4aa20a0530cc8f0ed948203",
          "sha256": "aab6d779b15cf815b0d80450ea8cec53f91b2020ba5286416ee60fc5e1bc2471",
          "sha1": "ed3c9bb0b011dc69e0e53fa16800015dfd5bbdf2",
          "md5": "aaa16623573652824f2084051399491b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 168685,
          "sha512": "0556e5a27060276cbbaaad64cc3650df52d1a403d5af0466080925a51a71d57c7e594f5ae728e65e1e90dd382b1f55c86bef56a7f4aa20a0530cc8f0ed948203",
          "sha256": "aab6d779b15cf815b0d80450ea8cec53f91b2020ba5286416ee60fc5e1bc2471",
          "sha1": "ed3c9bb0b011dc69e0e53fa16800015dfd5bbdf2",
          "md5": "aaa16623573652824f2084051399491b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "size": 97042419,
          "sha512": "f3db1468558c84c279ac65f75f6fbeea8b290e5eec15cb234934abfe429b878a019a31074438516bacc52767144eb6e68deac60fa7f04cf2ea34ccaf23b7c819",
          "sha256": "cc79ee8c33d3a50306a3973199969af2fb7e9eb5d870c2a65709c34baad2c292",
          "sha1": "0dfb64ce45dfaca84dac449d9da01187f5d4267f",
          "md5": "32725e070f398c5f18503e30620aeb77"
        }
      ]
    }
  ]
}
