{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 154204,
          "sha512": "7e7e7884fa1ffde62374cb53450b38e944962f45305210132f44ba83057a26e19997fbe7e5cd26f5a36267f2f6dafa28433862ecbfbcda7ef604ac2b44b3d022",
          "sha256": "c97ac5ff6a41da3faa295f994d66bde789f6d6a9d13db94b7e8d03b4fe28032c",
          "sha1": "ef0d4ca4d4ef29c5ad3dea79cb467e5ed72908cd",
          "md5": "c144d1916ebc193cc5f373e47353d9cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "1.3.35"
          }
        },
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.35"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 154204,
          "sha512": "7e7e7884fa1ffde62374cb53450b38e944962f45305210132f44ba83057a26e19997fbe7e5cd26f5a36267f2f6dafa28433862ecbfbcda7ef604ac2b44b3d022",
          "sha256": "c97ac5ff6a41da3faa295f994d66bde789f6d6a9d13db94b7e8d03b4fe28032c",
          "sha1": "ef0d4ca4d4ef29c5ad3dea79cb467e5ed72908cd",
          "md5": "c144d1916ebc193cc5f373e47353d9cd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "size": 96987182,
          "sha512": "18a709aac91acd77e25b00adc981068f5b59b033ceba3f57ea12fc00cd78ad09f4fa7fca876050622e0d77373b02a5b79fc4876bdc02ab2cd2285a79b1f13417",
          "sha256": "660be0b653c2a9d73aca3b0e40602f63cd814837bbfba720845b94ca66a9c620",
          "sha1": "12a1b4a65809d8abaa9c0d55041dc3d69acbb6ff",
          "md5": "bea658ad23d0658433e084eeccd143cc"
        }
      ]
    }
  ]
}
