{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.3-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 162333,
          "sha512": "9bd0abe5989cfbefd23cdd685f075c5f6906138939c8c2f715a7f1c662a3158598af142ab93888aa1b72cffc73c5964ced09aa9966180ec933a86f6885bcd524",
          "sha256": "99e42f2f934e449f7480fa5920487c15cc690617178ed2e3143a766e0f8d6ed5",
          "sha1": "89b07a2a5ded9462a8a1bddd83d0aa4fa9dc8eec",
          "md5": "c2a24b56fd58ab342109846e5d8873d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.38"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL.jar",
          "size": 162333,
          "sha512": "9bd0abe5989cfbefd23cdd685f075c5f6906138939c8c2f715a7f1c662a3158598af142ab93888aa1b72cffc73c5964ced09aa9966180ec933a86f6885bcd524",
          "sha256": "99e42f2f934e449f7480fa5920487c15cc690617178ed2e3143a766e0f8d6ed5",
          "sha1": "89b07a2a5ded9462a8a1bddd83d0aa4fa9dc8eec",
          "md5": "c2a24b56fd58ab342109846e5d8873d9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.3-TRIAL-all.jar",
          "size": 97066206,
          "sha512": "9bd0b4b057a8f6e05074cd9e3a12b759a9374ea9ffb353436d61d389933ad91e3c328a80e0d2f332de919e959b556dcd2b152e6e39036bdc648ee168c734e4b9",
          "sha256": "85586a3527f9d79fa72ea6b49a1fa8484280c99bd8f25ec5d244cb755e74c3eb",
          "sha1": "c49c7a47d3228d4cff8b778c6da23b5e554025ee",
          "md5": "990d3c84fce6ec299a99bdf7162b5c8c"
        }
      ]
    }
  ]
}
