{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.6-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.6-TRIAL.jar",
          "url": "specmatic-grpc-0.0.6-TRIAL.jar",
          "size": 188465,
          "sha512": "0bbe190bfa7014445440c4807fdb5401bc1f8fcf252eaa7522b94005d7fc02122a6fc81b7c6ba22b0a1ca0ccd747cff8ea8396a8f665ea25d63f5ce8e425697e",
          "sha256": "afcd1b3c87abdf642a96f16edd97c211ae2e61fcb0e8b4d39003ce2873cf2e88",
          "sha1": "926ec4fcfc9d6775c8b662f9bf917d72461577c8",
          "md5": "58d0a7525987df2d99265c9ac3b82425"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.6-TRIAL.jar",
          "url": "specmatic-grpc-0.0.6-TRIAL.jar",
          "size": 188465,
          "sha512": "0bbe190bfa7014445440c4807fdb5401bc1f8fcf252eaa7522b94005d7fc02122a6fc81b7c6ba22b0a1ca0ccd747cff8ea8396a8f665ea25d63f5ce8e425697e",
          "sha256": "afcd1b3c87abdf642a96f16edd97c211ae2e61fcb0e8b4d39003ce2873cf2e88",
          "sha1": "926ec4fcfc9d6775c8b662f9bf917d72461577c8",
          "md5": "58d0a7525987df2d99265c9ac3b82425"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.6-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.6-TRIAL-all.jar",
          "size": 99622119,
          "sha512": "37dc325a96fc68da34153b294ea5b007b1dd7b2f2fa4021b809d3eb173608bd2eb59dd5bf538bf01a1aae8c23413a2b016ccb4aa9023573a0317c33fe5fee5bc",
          "sha256": "b304407e83e755f1bc430302afd57cbb4d713cd508be82c97c00b65dc7953437",
          "sha1": "07c2c17245f0ee798df00e521688e23537cb3cbf",
          "md5": "d494561569ac6144bbff95b8ee9deaf7"
        }
      ]
    }
  ]
}
