{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.7-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.7-TRIAL.jar",
          "url": "specmatic-grpc-0.0.7-TRIAL.jar",
          "size": 188462,
          "sha512": "9b5b92c7f0ce449fdc910610c843584bd1c09021945190bf8bd5c40731b39505f4438a92c94159be5727205c556cf9e126b94b47176068fafb6dda6ac809331c",
          "sha256": "7df04abc3f95a53df94291d79c8b5309d7aaeb7369e7f36312c8c0f339e05fd8",
          "sha1": "7bd110c0dac0ea5b95e3d7aeaaa0f49cc66f5556",
          "md5": "75bc4703fad3e0069c59fa0d9011ba3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.13"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.7-TRIAL.jar",
          "url": "specmatic-grpc-0.0.7-TRIAL.jar",
          "size": 188462,
          "sha512": "9b5b92c7f0ce449fdc910610c843584bd1c09021945190bf8bd5c40731b39505f4438a92c94159be5727205c556cf9e126b94b47176068fafb6dda6ac809331c",
          "sha256": "7df04abc3f95a53df94291d79c8b5309d7aaeb7369e7f36312c8c0f339e05fd8",
          "sha1": "7bd110c0dac0ea5b95e3d7aeaaa0f49cc66f5556",
          "md5": "75bc4703fad3e0069c59fa0d9011ba3d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.7-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.7-TRIAL-all.jar",
          "size": 99622116,
          "sha512": "f04f7ecc4c0cf658596ed970f9d7f47a00d8ef3b3bd7e55f0aceefd53115430e90272a58ac0a5cb53ec30e1be55dcea4453932ecbb314ef5bfa0488ed4ecda6d",
          "sha256": "21b531079319c95662500d958b7efa1c9399c0d1aea6f7024e4b9737af705c13",
          "sha1": "ca0a4ad1307bab16b34bd398b82664c97e6019b8",
          "md5": "100fa58f2c7cc8723c555cef14ba8644"
        }
      ]
    }
  ]
}
