{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.12-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.12-TRIAL.jar",
          "url": "specmatic-grpc-0.0.12-TRIAL.jar",
          "size": 189624,
          "sha512": "55e22bf8d347d13b08314825283eec2e8336f603d4d3458e13d3f1c64639f5e5475d221b36f3b7e283eb27e6c61eb52e550aeb808071187d3e8e83b43367c29e",
          "sha256": "6d101ad981405cc32af8ad87dccb7c68c46da10e122585d374755fbf86df5ba0",
          "sha1": "6945432604dc621cf1f60f917dc172f6525eedfa",
          "md5": "c592c63f6cf2ede0efaecd994d90dd1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.12-TRIAL.jar",
          "url": "specmatic-grpc-0.0.12-TRIAL.jar",
          "size": 189624,
          "sha512": "55e22bf8d347d13b08314825283eec2e8336f603d4d3458e13d3f1c64639f5e5475d221b36f3b7e283eb27e6c61eb52e550aeb808071187d3e8e83b43367c29e",
          "sha256": "6d101ad981405cc32af8ad87dccb7c68c46da10e122585d374755fbf86df5ba0",
          "sha1": "6945432604dc621cf1f60f917dc172f6525eedfa",
          "md5": "c592c63f6cf2ede0efaecd994d90dd1a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.12-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.12-TRIAL-all.jar",
          "size": 99708409,
          "sha512": "cb7698ee0c04c4a3cd85fae72d3595c1188b406d26bc8cb2abe8eaeb87ff9d74421f76bdc0c57e82747226ecbe7501aba02219abdd0217c251dd017dc2a59f25",
          "sha256": "16524a4246f92c7e1d026ed4ae2e4563aa27cee03fa5cd275e1e0bf07c789f2d",
          "sha1": "294194b44c1c44aea2e254f82e5348d4d1b5ba16",
          "md5": "2243d1c9ff9b84c165dcc4b750c7a9cd"
        }
      ]
    }
  ]
}
