{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.8-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.8-TRIAL.jar",
          "url": "specmatic-grpc-0.0.8-TRIAL.jar",
          "size": 188462,
          "sha512": "81861bea24458c347dd09d4360dc0f01e896b06ebaaf35ac5fd10dd1da63b96731d6d5783933db6e7ec92cf25395f6d0975e80215672314309b884f6087e47b7",
          "sha256": "55cb4d063703e480b6d7db9b5321a317bffa2dfa9c39c0f30884d195fd7112c2",
          "sha1": "b8bb28b305f2a3d77c36cc0222cc714e383448f3",
          "md5": "30b5aed78e754767e61deff2194611a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.8-TRIAL.jar",
          "url": "specmatic-grpc-0.0.8-TRIAL.jar",
          "size": 188462,
          "sha512": "81861bea24458c347dd09d4360dc0f01e896b06ebaaf35ac5fd10dd1da63b96731d6d5783933db6e7ec92cf25395f6d0975e80215672314309b884f6087e47b7",
          "sha256": "55cb4d063703e480b6d7db9b5321a317bffa2dfa9c39c0f30884d195fd7112c2",
          "sha1": "b8bb28b305f2a3d77c36cc0222cc714e383448f3",
          "md5": "30b5aed78e754767e61deff2194611a6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.8-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.8-TRIAL-all.jar",
          "size": 99707247,
          "sha512": "e203ad58b86d817db62be97ecb0598c17172b0ca7c1fd8ff035ac19444ae85caa7bb6c178b91585382ea146d9989160901a11a39a9101c583309b3b9b06dc60a",
          "sha256": "1cc19078f3db8c0eba15936ddd227c829014082e57c475177e3ca446054287bc",
          "sha1": "de89d7d676f1b23fdffade96f90626ba6f4ce4f6",
          "md5": "9b783110b22c470fee09f8540178a40a"
        }
      ]
    }
  ]
}
