{
  "formatVersion": "1.1",
  "component": {
    "group": "in.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.2-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.2-TRIAL.jar",
          "url": "specmatic-grpc-0.0.2-TRIAL.jar",
          "size": 127069,
          "sha512": "f89980ebf4ece4ae0b8fe0ab9a435090ce112063c0689c9321a85e16760d9150af54935f3190d0f92154816da1efd08084d4a876a38b34df4f2eb6dadeed96ac",
          "sha256": "2ab496fd038c92a5c48ffe2fb58e8317ae5bf71de38e2e590d08fb229bcd1b8c",
          "sha1": "2051da43789896d863bddadb29746ec009fea165",
          "md5": "3a2c633e03806dee9dc07b53adfc075f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "in.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "1.3.32"
          }
        },
        {
          "group": "in.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "1.3.32"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.2-TRIAL.jar",
          "url": "specmatic-grpc-0.0.2-TRIAL.jar",
          "size": 127069,
          "sha512": "f89980ebf4ece4ae0b8fe0ab9a435090ce112063c0689c9321a85e16760d9150af54935f3190d0f92154816da1efd08084d4a876a38b34df4f2eb6dadeed96ac",
          "sha256": "2ab496fd038c92a5c48ffe2fb58e8317ae5bf71de38e2e590d08fb229bcd1b8c",
          "sha1": "2051da43789896d863bddadb29746ec009fea165",
          "md5": "3a2c633e03806dee9dc07b53adfc075f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.2-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.2-TRIAL-all.jar",
          "size": 96977438,
          "sha512": "6b81c6f208387de957dcc12586253a2a982ecec7a70c01db1e43b01e877a23c6f9e5e28ca989d47cac32bdb4a12f75a7067d3e117e1e964c66f58f6358f100d5",
          "sha256": "2a1f2b0f0450e55f7f5603a0c849ccb6a26bef878566a24ca11abe0b07129ecf",
          "sha1": "f6b04fea5e708aba0e471260dbd7d2cb44547dd0",
          "md5": "6161e9652ed24c1b130155f4cabbe473"
        }
      ]
    }
  ]
}
